# .github/actions/actiondockerpush/action.yml
name: Docker Push Action
description: "Create tag"
runs:
  using: "composite"
  steps:
    - name: Coger variables de package.json
      run: |
        VERSION=$(node -p "require('./package.json').version")
        NAME=$(node -p "require('./package.json').name")
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "NAME=$NAME" >> $GITHUB_ENV
      shell: bash
    - name: Generate full image tags
      id: generate_full_image_tags
      run: |
        full_tags="${{ inputs.docker_username }}/${{ inputs.image_name }}:${{ inputs.version }}"
        echo "full_image_tags=$full_tags" >> $GITHUB_ENV  
      shell: bash
