name: Docker Push Action
description: "Push Docker image to DockerHub"
inputs:
  image_name:
    description: "The Docker image name"
    required: true
  version:
    description: "Version tag for the Docker image"
    required: true
  docker_username:
    description: "DockerHub username"
    required: true
  docker_password:
    description: "DockerHub password"
    required: true
outputs:
  full_image_tags:
    description: "Full Docker image tag and latest tag"
runs:
  using: "composite"
  steps:
    - name: echo vars
      run: |
        full_tags="${{ inputs.image_name }}:${{ inputs.version }} ${{ inputs.image_name }}:latest"
        echo "full_image_tags=$full_tags" >> $GITHUB_ENV
      shell: bash
