name: CD
on:
 workflow_call:
jobs:
  pull-DockerFiles:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Pull Dockerfile
        run: |
         docker pull ${{ needs.CI.outputs.image_tags }}
      - name: Run Docker container
        run: |
          docker run -d --name angular_aplication -p 80:8080 ${{ needs.CI.outputs.image_tags }}

      - name: Wait 30 seconds for container to start 
        run: sleep 30
      - name: Docker ps
        run: |
          docker ps

      - name: Curl the deployed application
        run: |
          curl -I http://localhost:80
        