name: CD
on:
 workflow_call:
jobs:
  pull-DockerFiles:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Pull Dockerfile
        run: |
          docker pull ${{ env.full_image_tags }}
      - name: Run Docker container
        run: |
          docker run -d --name angular_aplication -p 80:80 ${{ env.full_image_tags }}
      - name: Wait 10 seconds for container to start 
        run: sleep 10
      - name: Curl the deployed application
        run: |
          curl -I http://localhost:80  
        