name: CD
on:
 workflow_call:
jobs:
  pull-DockerFiles:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Pull Dockerfile
        run: |
         docker pull vsanchezr33/sample-angular-app:0.0.1
      - name: Run Docker container
        run: |
          docker run -d --name angular_aplication -p 80:80 vsanchezr33/sample-angular-app:0.0.1

      - name: Wait 10 seconds for container to start 
        run: sleep 20
      - name: execute command
        run: |
         docker exec -it angular_aplication ls /usr/share/nginx/html

      - name: Curl the deployed application
        run: |
          curl -I http://localhost:80  
        