name: CI
on:
  workflow_call:
      
    
jobs:
 
  job1:
    runs-on: ubuntu-latest
    outputs:
      full_image_tags: ${{ steps.vars.outputs.full_image_tags }}
    needs: build
    environment: development
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Coger variables de package.json
        run: |
              VERSION=$(node -p "require('./package.json').version")
              NAME=$(node -p "require('./package.json').name")
              echo "VERSION=$VERSION" >> $GITHUB_ENV
              echo "NAME=$NAME" >> $GITHUB_ENV
      - name: crear tag
        uses: ./.github/actions/actiondockerpush
        with:
          image_name: '${{ env.NAME }}'
          version: '${{ env.VERSION }}'
          docker_username: ${{ secrets.USERNAME }}
         

      - name: Echo full image tags from action
        run: |
         echo " ${{ env.full_image_tags }}"
      
      - name: Create a output variable
        id: vars
        run: |
          echo "full_image_tags=${{ env.full_image_tags }}" >> $GITHUB_OUTPUT
      

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.full_image_tags }} .

          
      - name: Push Docker image to DockerHub
        run: docker push ${{ env.full_image_tags }}