name: CI
on:
  workflow_call:
    outputs: 
      tag: ${{ jobs.job1.outputs.tag }}

jobs:
  build:
    name: build angular project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  job1:
    runs-on: ubuntu-latest
    needs: build
    environment: development
    outputs:
       tag: ${{ env.full_image_tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Coger variables de package.json
        run: |
          VERSION=$(node -p "require('./package.json').version")
          NAME=$(node -p "require('./package.json').name")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "NAME=$NAME" >> $GITHUB_ENV

      - name: crear tag
        uses: ./.github/actions/actiondockerpush
        with:
          image_name: '${{ env.NAME }}'
          version: '${{ env.VERSION }}'
          docker_username: ${{ secrets.USERNAME }}

      - name: Set full image tags
        run: echo "full_image_tags=${{ env.NAME }}:${{ env.VERSION }}" >> $GITHUB_ENV

      - name: Echo full image tags from action
        run: echo "${{ env.full_image_tags }}"

      - name: Create a output variable
        id: tag
        run: echo "tag=${{ env.full_image_tags }}" >> $GITHUB_OUTPUT 

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.full_image_tags }} .

      - name: Push Docker image to DockerHub
        run: docker push ${{ env.full_image_tags }}
