name: semanal1
on:
  workflow_dispatch:
jobs:
  entorno:
    uses: ./.github/workflows/entorno.yml
  CI:
    needs: entorno
    uses: ./.github/workflows/CI.yaml
    with:
      entorno: ${{ needs.entorno.outputs.entorno }}
    secrets: inherit

  CD:
    needs: [CI,entorno]
    uses: ./.github/workflows/CD.yml
    with:
      image_name: ${{ needs.CI.outputs.image_name }}
      entorno: ${{needs.entornos.outputs.entorno}}
    secrets: inherit

  Echo_Output:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Echo image_name
        run: echo "${{ needs.CI.outputs.image_name }}"
