name: semanal1
on:
  push:
    branches:
      - development
      - main
  pull_request:
    types:
      - closed

jobs:
  CI:
    uses: ./.github/workflows/CI.yaml
    secrets: inherit
  CD:
    if: github.ref == 'refs/heads/development'
    needs: CI
    uses: ./.github/workflows/CD.yml
    secrets: inherit