name: semanal1
on:
  push:
    branches:
      - development
      - main
  pull_request:
    types:
      - closed

jobs:
  CI:
    if: github.ref == 'refs/heads/development'
    uses: ./.github/workflows/CI.yaml
    secrets: inherit
  echo_output:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Echo output
        run: echo ${{ needs.CI.outputs.tag }}
  CD:
    needs: CI
    uses: ./.github/workflows/CD.yml
    with:
      image_name: ${{ needs.CI.outputs.tag  }}
    secrets: inherit